SELECT
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4) AS '誕生年',
	COUNT(id) AS 'COUNT(id)'
FROM
	players
WHERE
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4) = '1980'
GROUP BY
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4)

UNION

SELECT
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4) AS '誕生年',
	COUNT(id) AS 'COUNT(id)'
FROM
	players
WHERE
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4) = '1981'
GROUP BY
	SUBSTRING(CAST(birth AS VARCHAR), 1, 4);